name: Cherry-pick request
description: Provide commit IDs to cherry-pick into a specific branch. **Please, do NOT forget to milestone this.** If this is not milestoned, then the cherry-picks will not trigger.
# labels: ["type: bug", "untriaged"]
# assignees:
#   - pavank1992
#   - sgowroji
#   - iancha1992
body:
  - type: textarea
    id: commit_ids
    attributes:
      label: >
        Please put the commit IDs (at least first 6 digits of the commit IDs). If multiple, then please separate by commas.
        Example: 9e90a6, f1da12
  - type: dropdown
    id: subteam
    attributes:
      label: >
        Which category does this issue belong to?
      description: >
        Please, add a label(s). If you cannot find a label you want, then please add the label to the PR on your own when its created.
      multiple: true
      options:
        - team-CLI
        - team-OSS
        - team-Core
        - team-Bazel
        - team-Android
        - z-team-Apple
        - team-Rules-API
        - team-Rules-CPP
        - team-Local-Exec
        - team-Rules-Java
        - team-Rules-ObjC
        - team-Loading-API
        - team-Performance
        - team-Remote-Exec
        - team-ExternalDeps
        - team-Rules-Python
        - team-Rules-Server
        - team-Documentation
        - team-Configurability
        - team-Starlark-Integration
        - team-Starlark-Interpreter
  - type: textarea
    id: reviewer
    attributes:
      label: >
        Please provide the reviewers of the PR once it is created after cherry-picking.
        Example: @iancha1992, @keertk
