name: cherry-picker-on-open

on:
  issues:
    types: [milestoned]

env:
  GH_TOKEN: ${{ secrets.BAZEL_IO_TOKEN }}

jobs:
  trigger-cherrypick-on-comment:
    if: startsWith(github.event.issue.body, 'Forked from')
    runs-on: ubuntu-latest
    steps:
      - name: Logging github event
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: Run cherrypicker on comment
        uses: iancha1992/continuous-integration/actions/cherry_picker@feature-cherrypick-phase2
        with:
          triggered-on: commented
          pr-number: ${{ github.event.issue.body }}
          milestone-title: ${{ github.event.milestone.title }}
          milestoned-issue-number: ${{ github.event.issue.number }}
          is-prod: False
  trigger-cherrypick-ondemand:
    if: startsWith(github.event.issue.body, '@bazel-io cherry-pick')
    runs-on: ubuntu-latest
    steps:
      - name: Logging github event
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: Run cherrypicker on demand
        uses: iancha1992/continuous-integration/actions/cherry_picker@feature-cherrypick-phase2
        with:
          triggered-on: ondemand
          milestone-title: ${{ github.event.milestone.title }}
          milestoned-issue-number: ${{ github.event.issue.number }}
          issue-title: ${{ github.event.issue.title }}
          issue-body: ${{ github.event.issue.body }}
          is-prod: False
