name: cherry-picker-on-close

on:
  pull_request_target:
    types: [closed]
  issues:
    types: [closed]

env:
  GH_TOKEN: ${{ secrets.BAZEL_IO_TOKEN }}

jobs:
  cherry-picker-on-close:
    # if: github.event.sender.login == 'copybara-service[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Logging github event
        run: echo '${{ github.event }}'
      - name: Run cherrypicker on close
        uses: iancha1992/continuous-integration/actions/cherry_picker@feature-cherrypick-phase2
        with:
          triggered-on: closed
          pr-number: ${{ github.event.number }}
          is-prod: False
