name: cherry-picker-on-comment

on:
  # workflow_run:
  #   workflows: ["release-helper"]
  #   types:
  #     - completed
  # issue:
  #   types:
  #     [created]
  issue:
    types: [created]


jobs:
  testing:
    # if: startsWith(github.event.comment.body, 'Forked from https://github.com/iancha1992/bazel/pull/')
    runs-on: ubuntu-latest
    # permissions:
    #   issues: write
    steps:
      - uses: actions/checkout@v2
      - name: Logging github event
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: Run helper
        uses: iancha1992/continuous-integration/actions/cherry-picker/on-comment@release_test # master
        with:
          token: ${{ secrets.BAZEL_IO_TOKEN }}

