name: cherry-picker-on-comment

on:
  # workflow_run:
  #   workflows: ["release-helper"]
  #   types:
  #     - completed
  # issue:
  #   types:
  #     [created]
  issues:
    types: [opened]


jobs:
  testing:
    if: startsWith(github.event.issue.body, "Forked from ")
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Logging github event
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: Run helper
        uses: iancha1992/continuous-integration/actions/cherry-picker/on-comment@release_test # master
        with:
          token: ${{ secrets.BAZEL_IO_TOKEN }}

