name: cherry-picker-on-close
on:
  pull_request:
    types: [closed]
permissions:
  contents: read

jobs:
  cherry-pick-on-close:
    runs-on: ubuntu-latest
    steps:
      - name: Check if cherry-pickable
        uses: iancha1992/continuous-integration/actions/cherry-picker@release_test


    



