name: cherry-picker-on-close

on:
  # maybe make it more specific (closed by the cpybara)
  pull_request:
    types: [closed]

env:
  GH_TOKEN: ${{ secrets.BAZEL_IO_TOKEN }}

jobs:
  cherry-picker-on-close:
    runs-on: ubuntu-latest
    steps:
      - name: Logging github event
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: Run cherrypicker on close
        uses: iancha1992/continuous-integration/actions/cherry-picker@feature-cherrypick
        with:
          triggered-on: closed
          pr-number: ${{ github.event.number }}
          # milestone-title: "0"
          # milestoned-issue-number: "0"
          is-prod: False
