name: Issues with security!
on:
  issues:
    types: [opened]
jobs:
  print_issue_title:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue title
        uses: iancha1992/continuous-integration/actions/demonstratingsecurity@thisisjusttesting
        with:
          issue-title: ${{ github.event.issue.title }}
