name: Add issue labels

on:
  issues:
    types: [opened, edited]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Logging github event
        run: echo '${{ toJSON(github.event) }}' | jq
      - name: Read the inputs
        shell: bash
        run: |
          echo helllllo worldddddddd!!!!
