name: Add issue labels

on:
  issues:
    types: [opened, edited]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      # - name: Logging github event
      #   run: echo a${{ toJSON(github.event.issue.body) }}a | jq
      - name: Read the inputs
        shell: bash
        env:
          Issue_Body: ${{ toJSON(github.event.issue.body) }}
        run: |
          echo hiya
          rightpart=${Issue_Body#*Which category does this issue belong to?}
          output=${rightpart%"What's the simplest, easiest way to reproduce this bug?"*}
          echo $output
          echo byebye!!!!!
