name: Add issue labels based on the inputs from the issuer

on:
  issues:
    types: [opened, edited]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Read the inputs
        shell: bash
        run: |
          echo helllllo worldddddddd!!!!
