name: Add issue labels

on:
  issues:
    types: [opened, edited]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Feature request labeler
        if: contains(github.event.issue.body, 'Description of the feature request')
        shell: bash
        env:
          Issue_Body: ${{ toJSON(github.event.issue.body) }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          # output="\n\n\nC++/Objective-C Rules, Core, Local Execution\n\n###"
        run: |
          echo "$Issue_Body"
          rightpart=${Issue_Body#*Which category does this issue belong to?}
          output=${rightpart%"What underlying problem are you trying to solve with this feature?"*}
          new_string=$(echo "$output" | sed 's/\\n//g; s/#//g')
          echo this is the new string!!!!!
          echo $new_string
        

      - name: Bug report labeler
        if: contains(github.event.issue.body, 'Description of the bug')
        shell: bash
        env:
          Issue_Body: ${{ toJSON(github.event.issue.body) }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          # output="\n\n\nC++/Objective-C Rules, Core, Local Execution\n\n###"
        run: |
          echo "$Issue_Body"
          rightpart=${Issue_Body#*Which category does this issue belong to?}
          output=${rightpart%"What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible"*}
          new_string=$(echo "$output" | sed 's/\\n//g; s/#//g')
          echo this is the new string!!!!!
          echo $new_string

          python - << EOF

          myPyString = "Do something on python"
          print(myPyString)
          print("Hello world!!!!")

          EOF
        


