name: lockfiles-update-all-platforms

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: read

env:
  GH_TOKEN: ${{ secrets.BAZEL_IO_TOKEN }}

jobs:
  update-on-ubuntu:
    if: contains(github.event.label.name, 'update-lockfiles-on-all-platforms')
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: Clone the repo & update the lockfile(s)
        uses: iancha1992/continuous-integration/actions/all-platform-lockfiles/ubuntu-os@all_platform_update

  update-on-mac-intel:
    needs: [update-lockfiles-on-ubuntu]
    runs-on: macos-13
    steps:
      - name: Clone the repo & update the lockfile(s)
        uses: iancha1992/continuous-integration/actions/all-platform-lockfiles@all_platform_update
      # - name: hihihi
      #   run: |
      #     uname -m
      #   shell: bash
