name: lockfiles-update-all-platforms

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: read

env:
  GH_TOKEN: ${{ secrets.BAZEL_IO_TOKEN }}

jobs:
  if: contains(github.event.label.name, 'update-lockfiles-on-all-platforms')
  update-lockfiles-on-all-platforms:
    runs-on: macos-13
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - name: commando
        run: |
          uname -m
        shell: bash

      # - name: Run helper
      #   uses: bazelbuild/continuous-integration/actions/release-helper@b9b7f0dad8ab00a48cc262d1d38339a1dd11c7c5 # master
      #   with:
      #     token: ${{ secrets.BAZEL_IO_TOKEN }}
# on:
#   pull_request:
#     types:
#       - labeled

# env:
#   GH_TOKEN: ${{ secrets.BAZEL_IO_TOKEN }}

# jobs:
#   update-lockfile:
#     runs-on: ubuntu-latest
#     if: contains(github.event.label.name, 'updatelock')
