name: update-lockfiles

on:
  pull_request:
    branches:
      - "release-**"
    types:
      - closed

permissions:
  contents: read

env:
  GH_TOKEN: ${{ secrets.BAZEL_IO_TOKEN }}

jobs:
  update-lockfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
        with:
          egress-policy: audit
      - name: Update lockfile(s) on closed PR
        uses: bazelbuild/continuous-integration/actions/update-lockfile@122ce87694d0dd505a019321a04f8e64378bddbd
        with:
          release-branch: ${{ github.base_ref }}
          is-prod: True
          pr-number: ${{ github.event.number }}
