name: Update Lockfile

on:
  pull_request:
    types:
      - labeled

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    if: contains(github.event.label.name, 'updatelock')
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      # - name: Mount bazel cache
      #   uses: actions/cache@v1
      #   with:
      #     path: "/home/runner/.cache/bazel"
      #     key: bazel
      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: Update Lockfile
        run: |
          # "${GITHUB_WORKSPACE}/bin/bazel" run //src/test/tools/bzlmod:update_default_lock_file
          "${GITHUB_WORKSPACE}/bin/bazel" mod deps --lockfile_mode=update
          echo hello world!
          git branch
          git diff
